// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBErTsXlrXB0TnQw_jF_6o5GrK0z-TyXhA',
    appId: '1:125054942606:web:1698371b50075e9eabb8df',
    messagingSenderId: '125054942606',
    projectId: 'dna-holidays',
    authDomain: 'dna-holidays.firebaseapp.com',
    storageBucket: 'dna-holidays.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOoUX4MvN0uSkRmxBqOiPcY35Er5DeuRA',
    appId: '1:125054942606:android:49d2f8e372f39c36abb8df',
    messagingSenderId: '125054942606',
    projectId: 'dna-holidays',
    storageBucket: 'dna-holidays.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMRASVXE_satmKwDAGGmkWFUdZ9jBiOZ4',
    appId: '1:125054942606:ios:b8ff1143f7ad5cc3abb8df',
    messagingSenderId: '125054942606',
    projectId: 'dna-holidays',
    storageBucket: 'dna-holidays.appspot.com',
    iosBundleId: 'com.gofly',
  );
}
